-- EVENTS table
create table events (
    id bigint generated by default as identity primary key,
    title text not null,
    date date not null,
    description text not null,
    image_url text,
    created_at timestamp default now()
);

-- BOARD MEMBERS table
create table board_members (
    id bigint generated by default as identity primary key,
    name text not null,
    position text not null,
    year text not null,
    image_url text,
    created_at timestamp default now()
);

-- GALLERY table
create table gallery (
    id bigint generated by default as identity primary key,
    image_url text not null,
    caption text,
    created_at timestamp default now()
);

-- ABOUT table
create table about (
    id bigint generated by default as identity primary key,
    welcome_title text not null,
    about_text text not null,
    created_at timestamp default now()
);

-- CONTACT FORM SUBMISSIONS table
create table contact_form_submissions (
    id bigint generated by default as identity primary key,
    name text not null,
    email text,
    phone text,
    message text not null,
    created_at timestamp default now()
);
